# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/lucye/vsc/ORBS-seperated

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/lucye/vsc/ORBS-seperated

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/c/Users/lucye/vsc/ORBS-seperated/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lucye/vsc/ORBS-seperated/CMakeFiles /mnt/c/Users/lucye/vsc/ORBS-seperated//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lucye/vsc/ORBS-seperated/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ORBS

# Build rule for target.
ORBS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ORBS
.PHONY : ORBS

# fast build rule for target.
ORBS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/build
.PHONY : ORBS/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/CMakeFiles/uninstall.dir/build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

Theme.o: Theme.cpp.o
.PHONY : Theme.o

# target to build an object file
Theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/Theme.cpp.o
.PHONY : Theme.cpp.o

Theme.i: Theme.cpp.i
.PHONY : Theme.i

# target to preprocess a source file
Theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/Theme.cpp.i
.PHONY : Theme.cpp.i

Theme.s: Theme.cpp.s
.PHONY : Theme.s

# target to generate assembly for a file
Theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/Theme.cpp.s
.PHONY : Theme.cpp.s

atom.o: atom.cpp.o
.PHONY : atom.o

# target to build an object file
atom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/atom.cpp.o
.PHONY : atom.cpp.o

atom.i: atom.cpp.i
.PHONY : atom.i

# target to preprocess a source file
atom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/atom.cpp.i
.PHONY : atom.cpp.i

atom.s: atom.cpp.s
.PHONY : atom.s

# target to generate assembly for a file
atom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/atom.cpp.s
.PHONY : atom.cpp.s

fileio.o: fileio.cpp.o
.PHONY : fileio.o

# target to build an object file
fileio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/fileio.cpp.o
.PHONY : fileio.cpp.o

fileio.i: fileio.cpp.i
.PHONY : fileio.i

# target to preprocess a source file
fileio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/fileio.cpp.i
.PHONY : fileio.cpp.i

fileio.s: fileio.cpp.s
.PHONY : fileio.s

# target to generate assembly for a file
fileio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/fileio.cpp.s
.PHONY : fileio.cpp.s

instancing.o: instancing.cpp.o
.PHONY : instancing.o

# target to build an object file
instancing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/instancing.cpp.o
.PHONY : instancing.cpp.o

instancing.i: instancing.cpp.i
.PHONY : instancing.i

# target to preprocess a source file
instancing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/instancing.cpp.i
.PHONY : instancing.cpp.i

instancing.s: instancing.cpp.s
.PHONY : instancing.s

# target to generate assembly for a file
instancing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/instancing.cpp.s
.PHONY : instancing.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ORBS.dir/build.make CMakeFiles/ORBS.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... ORBS"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... Theme.o"
	@echo "... Theme.i"
	@echo "... Theme.s"
	@echo "... atom.o"
	@echo "... atom.i"
	@echo "... atom.s"
	@echo "... fileio.o"
	@echo "... fileio.i"
	@echo "... fileio.s"
	@echo "... instancing.o"
	@echo "... instancing.i"
	@echo "... instancing.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

